description: "This research project develops training material for rsearchers wanting to learn to build project websites in GitHun with GitHub Pages"
email: "team@carpentries.org"
github: "https://github.com/swcarpentry.org"

team_members:
  - name:" Tom Cat"
    role: "project lead"
    start_date: "2016-02-01"
  - name: " Jane Smith"
    role: maintainer
    start_date: "2018-03-15"
  - name: "Albert Hamilton"
    role: editer
    start_date: "2017-12-01"
 - name: "Alice Dauncy"
   role: developer
   start_date: "2020-09-15"
