description: "This research project develops training material for rsearchers wanting to learn to build project websites in GitHun with GitHub Pages"
email: "team@carpentries.org"
github: "https://github.com/swcarpentry.org"
